---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-secret-idrive"
  labels:
    app.kubernetes.io/name: "${APP}"
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${SECRET_IDRIVE_S3_REPO}/${APP}
  RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${SECRET_IDRIVE_S3_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${SECRET_IDRIVE_S3_SECRET_KEY}
  RESTIC_PACK_SIZE: "60"

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-idrive"
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "30 2 * * *"
  restic:
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    pruneIntervalDays: 7
    repository: "${APP}-volsync-secret-idrive"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-8Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-local-path}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
