apiVersion: v1
kind: Secret
metadata:
  name: actual-secret
stringData:
  ACTUAL_NORDIGEN_SECRET_ID: ENC[AES256_GCM,data:xD538z7Av26ZNZzzO82V0p/Tqwh7FvDk6mQTt3v/bgNbcJ0y,iv:7NNwK8hf7V+mk2D38wE6rBC+IDw9nRsasdO2lLZYwzs=,tag:mlw0iEsBtPOEE3INmfKnhw==,type:str]
  ACTUAL_NORDIGEN_SECRET_KEY: ENC[AES256_GCM,data:D0VvpdZuG9KFwr3QRpIUQeFbDHAnMOo3zBaPWe6s9FDN6c9jENIWRVmlwOy7GdZShD2H1DAxLRe/Jib86RPFiGNLSbpbVLiIeiNpLYi/fUOq2FibPdEcuNpX/QGBVVaBzCy7PzFewTZ09wI1Adm3leGl4FjzIPtFvGxSVIxHwgo=,iv:W20fy2afs86gM64CMwtmC5Ja76nuzq1NB9hJFld6BkE=,tag:71I5YzQP+8ZXtwqqhnCmyA==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXpFQzEvRkFsUlhTaG1k
        cytRaUxsZUkvYzA3S0dObi9FaVNqTUtjc0dnCi9QU3IvVzdibXhaZm9pU01YaGNG
        TXdVK2ZQaVlWMGwvVlN1Q3ZvYlZ1M2cKLS0tIHEzZFh2eTZRL3daWmJGRHoyMExp
        a1NjWllSZzZDWDY2cDVMczhDV1FpVzgKZSitFEXhypzX1LrlTlradFS4+9I5C/YC
        F7qG7EBJJAw2ol1LQ+cco0Letzc+NAk3jwgyBHklqo+RSvwWlVeTrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T10:16:20Z"
  mac: ENC[AES256_GCM,data:Oc4A5Dt/M+8xNxKj/DMGAbxFXYq3YK1O8oG4jy4py4T/unBPoI+0NElHbDHOvkAsd6NMpEOvbkrtZgnjgFtcNRF5oloLCGezQUlvoMbCT14YOALB3bemix8GMbBLcnJ0pC8fYY3/qqBGIbaarY9vssfqvqrhkXQIVBe4p0RGxrs=,iv:NYtIyJa3ibodMAiFrRvwUcCaTCfCAxHhmuF0uaJVTiU=,tag:KJmNy5W5h4x+9cpIqfwJ7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
