apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:JkIHju3B3m8UtI4Ia2mrSNQkfckvBC16NNrQtww6bhWWan+gsUY29g==,iv:uCsjezzKnTrXUG4wCaXl8XDWYBzvRqH8argfmZvzNYM=,tag:NnlZQM63nxgkty2P7mZ5rA==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OU5nY1pnc2ltKzlSTGNz
            ZlFON0N4aVpoWnZ4MEFtSHViaFMzam5oNHdrClg2YzhrdGxSUEFjMUpBeU43V3Y2
            SXBQbDBIUEpZMXBPTVE5UTV3U2pkUlUKLS0tIFZjK0N6Q2dqMytWTEU5UlA3Rnhz
            bngxWHhXc0g0eEM4dWNSdmhqbzduTncKAworhCfGMh/MwL65Gl6P9eUCY91Hmqm2
            qNnHIif8vQ3MWU254cpwoDSOFgkjT18tqvIMAhlEo0V4q1JKTIR1MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T07:20:03Z"
    mac: ENC[AES256_GCM,data:oSujQNj2PN8MYr4Sv4fQbAhruJxknQDTIGZUCk5nln3UcD59fgO3bBq9BDu7ambd6JTqKR89J5BAjEJL2XDRcMNaWxhhiqYe9OpgyGOLceCbfau9ZFt7GgglsOR9Dw2+h8fxXaSQzbP9MErpId5oO9gHe1XvOGmjS53cntavvxU=,iv:64Cmy2X+T+UNlOlhkloZh3J/lHW2zwftI9hY+TEJn/4=,tag:9vyLRWdp7MbiHao7iuOa7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
