apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:aG2mCsutM03qc+HRwwaTydZbYn22ELCg2XZUJSKM0FUbETCnGU9uYA==,iv:re6SQz8SuEfHV7hiKy7GQDsO7yQs41SEjGq/gS8jEb0=,tag:7nGLgddDG4EHkSlxx3H9ig==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OU5nY1pnc2ltKzlSTGNz
        ZlFON0N4aVpoWnZ4MEFtSHViaFMzam5oNHdrClg2YzhrdGxSUEFjMUpBeU43V3Y2
        SXBQbDBIUEpZMXBPTVE5UTV3U2pkUlUKLS0tIFZjK0N6Q2dqMytWTEU5UlA3Rnhz
        bngxWHhXc0g0eEM4dWNSdmhqbzduTncKAworhCfGMh/MwL65Gl6P9eUCY91Hmqm2
        qNnHIif8vQ3MWU254cpwoDSOFgkjT18tqvIMAhlEo0V4q1JKTIR1MQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:33:07Z"
  mac: ENC[AES256_GCM,data:dOfqL2jZ/ZAWpxG8J5jL93UVdsZjrPK2nJnK32gBO/G4nfbk5Jq72a0b/g1Ji+2gnSsL9M+PESAVOmG9av0H3vy4kg4rgbXJi13/cTNFd4NuCXra5Kz142p7nKBhEHieBgLQh0+YkPlpCqwgwM/ukgz4dM4CNLoGlWdVQ9yw3Rw=,iv:QiK1z8JFUfCCofYeBn6H2VleEJ/QlknTE7CZ4gFVGvg=,tag:YksWU+r7Z555Lz/+Fkz1Xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
