apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:kIkStXqGMsRjYYdoMZE7Gek22VjRwLyhIpM+OQNqhQyxSsLokSBfJw==,iv:lM7oevvVX5ktRREPCVyVgPsa1aAdkMXTIFTWwebO2OQ=,tag:S16XuBU+MD52N0ExyGDJgw==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUzhKWXJWUWNTT0c1b2cz
        MnpjWEdFeWgwRGdzRHROTEZ4MGVDTWNTaVJjClBEcjBZS29OMWJJKythMis4Mm9T
        bUlzdVRUQXJ2enZYM0psdDFIQXdZdk0KLS0tIHBVMmIrMGVaNkYzVVJ0T28ra3Va
        emhabTdZM3IvNGlTTGM0b1I5MXNuWW8K5I1Cgc1cR0H+PC4kh/MxINOSovwx5M/w
        LtOKX8dsfz2mb/+zv1Zj3TlFsgGzoLe0p9jOQNkkEyMXe/fENcP6hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T22:16:16Z"
  mac: ENC[AES256_GCM,data:2flV6sf4ipTd+uUtA1uIn1xbJhmEvvU06FgAs3DQ/XH1aZCa4mXwsIUitPfwpOthR3nN1dx404Hsz2YyCoaRO0+DkiaqDbfNnxTEHrFtzVQinhCHdDGiGslWyzhsI5udPMYSya330xbrfSBHQP6YRhMh19YRm75CVEo/5qT4G+8=,iv:sCZKhUULrmyvbL2+xEcVxki5sJcq2jW0+DZ2fJf9KK8=,tag:4tvd4ry/FhOoNqE0EZjx0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
