apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password-secret
    namespace: monitoring
type: Opaque
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:7smdLv94MQ8IkykMwvdtTSejaPPcxEiU,iv:iLc9HxIWQRPw3qwRfKcggftD83jB/Ko7XnObqSROJ4w=,tag:8VvqSygAwe90TiGpJZ1Waw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NElIVzlla0VadlFXUDNQ
            MEhucWJKclpLcGdKVTk1dUVJTTJzbzF6RGpZClNsd0tGcG5zdXhMWlVTNmhUQ2w1
            eGFWS3FRM1c0RWd4YWtGNm9uK3VXZDAKLS0tICt1dFA1azQ0bXVNQzZabmY2Njda
            R3B0anVWN3d6cmgwdW02a2NWWEJHUDAK53lb9NxVUQRIlwr0kpK4oRAoz75AUrty
            7qr95RkRoeW+66w7PUd5UypvQvs5Kkw1MDnY4ANXaYbkel/rGMhrJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T07:23:10Z"
    mac: ENC[AES256_GCM,data:rpSdc5G5ABbFxskmXucDOxqLB3DK/j0N8sCnyiN+oi9ocUM49hDPDvvGRoPIZyvyMtLlkbzdErDRGHZ0nevKQKGPwntk6eZ+TGMsh/0swk9RQ3j4FcoXRzXZdVWp6elXZRoexOkgm/DlBe7UDpU1gQlGhJjUH7EyK07M/QvKq8Q=,iv:g5rF56LQQmzedDUaj8lWeNIe5hzb3hRMEJyN1DyT9CY=,tag:atAo7ULzGtw6voZODCecHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
