# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-garage-secret
    labels:
        app.kubernetes.io/name: ${APP}
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:pXVBhgvfbUkq23ac2jh+G9g2AIo+UZTsEqqrkNmyRvqzb/dP9UVQzslJoVqNOMUUfXfBZSAwzPGgZR0z+w==,iv:DxJHkuRMuOs1f6me2pAF9W4AeYqiNO0ZV/ko8ZpoOLs=,tag:bnSr7rYJfIW+4P2M9kbdVw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:n/8y2/CU4YjPLtKEV156rPxCzsZDiQ==,iv:PJN9p5NuUtD5k77DtqasHYwBrHaycpxj6YKhT74zbUY=,tag:Fdu3YWnkDMPyos8Xmt5Yqw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UvSivraUgju8kQpeX2f+dM8j133WvM/NifA=,iv:RZ+s+e1AXMiqY98uupFjKknGd4JsBNP1MXCOMrLsZd8=,tag:T6RMf1YSZxXf3hqc/pbdEQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ADkK1rN4HmsKXZIMkpi8fJtbi1vypEDNFQKA0VgSOFL1MhERs+BiU/EA4LFa+kURXHwZ76jx0RSK03KLfo8XWA==,iv:Jr/OHw0+79OkZx48tsUXlflRZ6HzFjfGF4YVDQfk6fI=,tag:JZ+IXvs4UXvYz+LzgB8Zvw==,type:str]
    RESTIC_PACK_SIZE: ENC[AES256_GCM,data:ydA=,iv:JN/w3hEv4B00PV6N8NSF2tESW8BNcFtT5sp0BhDMq9A=,tag:0mIrGFpVFUA3wOLO9BoBqw==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHFZcjFrQ0NTZXhLbG90
            cWRYVlhXRk5tSUlVcmdobU05VnphN0NNZ1VrClNjU1FocWxjYWRGT0JGM3lQNEtV
            UHVzbm54ODJ4dUliaG9VRDhKMk1UeTQKLS0tIDZHK1VkNmQ4b2NXYkIycXlBQUp0
            MkpQRlpYYUJ0YmUrYThzdVBXcUNZOFEKQtOlwba5KbAMcT4wMYRabmIXJRR5kDAk
            xK+bPlrZVoFjFzH3xcwu6czyvtz8GJz+AKtXBk1V3GzNHO8qK9osaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T00:01:31Z"
    mac: ENC[AES256_GCM,data:Lm5ZIgirJK2pG7vW1mKNioMHEfo5vQup3kuTgI4csJht4Gn8+3th52374cOCuHqtCVG8m5qR/jN5qXJDhYSpYighkcp3mKsS1E5SL7uLtfOEKhIhLKzMVKIh3fhBE0Nn70wVzdTbOjtNVmpXlOzjB16Z1jzCT7IH+NUBd28O1WM=,iv:cXH1S9qJXt5Y1orEsUSLIGJ5FdzNRAlve20zzCRSUdM=,tag:y6O8LwjBUcHR5cmRrzlqEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
