# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-nas
    labels:
        app.kubernetes.io/name: ${APP}
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:Bcd4SNiv51DNE3o=,iv:kIvWhHkVUH5TEAKeUE3hGdbWGcReRqZhV8C5HH3Q6yY=,tag:purIp6f7B8S6LJRe0WGVNQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:u6/vY7xPx8oZ106Tk6nbvK77NRs=,iv:CgAkV976Xu3ZrpF6cLniMInubD5McfJ0xraqoZNiM88=,tag:a59h+81flUlaIiszDrP8Ww==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:/ofwNJCgMgbdToWFlqFoxoXvTs8amD6g,iv:b7F/tdAuPmh4N9YQ+qc9lh4YnZapjFW1yn/gHJFx6gQ=,tag:Lhx3wGpVZOPMA1qY0zkVqw==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHFZcjFrQ0NTZXhLbG90
            cWRYVlhXRk5tSUlVcmdobU05VnphN0NNZ1VrClNjU1FocWxjYWRGT0JGM3lQNEtV
            UHVzbm54ODJ4dUliaG9VRDhKMk1UeTQKLS0tIDZHK1VkNmQ4b2NXYkIycXlBQUp0
            MkpQRlpYYUJ0YmUrYThzdVBXcUNZOFEKQtOlwba5KbAMcT4wMYRabmIXJRR5kDAk
            xK+bPlrZVoFjFzH3xcwu6czyvtz8GJz+AKtXBk1V3GzNHO8qK9osaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T20:16:06Z"
    mac: ENC[AES256_GCM,data:veTz5kPbW3/E3BRjfaOE5z21M/LdPETmuXniqbuGVg3TU5WMTWu1ywAjUIdwIDoFsOxnWIddPUO9bhIt8ye+N1FIpubzbGmNpcw9iBu4AffeK2ajKzyG7P5waxx2VjLcIzlD580IomyRS9XpiiDatjDTlTJBiZrkIZiB3G2i5+M=,iv:wkGYgSUoT5Fo6u1cgYruYysadrBscw34MomlW402E7Y=,tag:PpX9D8pSc7mbjBckXKA/hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
