apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/cGJdhZwPm51oQZTQg==,iv:+AMrEUwHHs4xQQjgqKS0dRMx2Xcc6EomY12CrNm2YvY=,tag:VHY3ECRs2jXKGbBeu/BtsQ==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMnYwMmlwcE9UY2pidCtS
        WXhWd01oU0QxNHJZc0t6bVZZN0pHcXdvOUhVClNSSWphWmZiL3VCWE5lZG5qQUVQ
        MHhzQ3V4L2FaMm5Xcm1wWDZnUnU5OVUKLS0tIFErYThaQlJMR3pkSW0yRG5mYjlv
        N3FHWm9qK3VEQWFIWTBFK3M1WUYwakEKJ1TX6iBJaa/MurcnWmqSEixz0hh6PGnt
        HZKzwXAyNPK6HPdD6zX3Zv+RWxOkEvaan1+XZDKy7bVA8TR1m8SdDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:33:07Z"
  mac: ENC[AES256_GCM,data:ugRELsGQrYfp1bQi7L/zNd1KmPU5xHJMmcpe+/kfFnRM1hdq0J5SjbAFRfesu5Nil+hLSoFWWpyXnJvME6PEFD2aYTZKPP2ORWMMtO5tP9RGlYOpYOtjNCDcoaxSz9lv6f9Blj4LrpgJlJt1JxJB5YhpEKYBu3YhLTuLxt5JyRI=,iv:JKA7UIQLzdGEPeAz3zuFCEPCxl1pDkcKkt8DqQnn69E=,tag:YnluIT+aTPz2KMHyln1Fhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
