apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:c6fxCTfnng1wjE1QZQ==,iv:39SusxMiDMtQiSGHTRw1f3o3Mfp0qwyqJasKdq+ngEQ=,tag:MwwKWaN1dDpazHXLtdTskQ==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMEVGSC9PY2crMm1FMXJG
        U09RWm1vNTBzcG1uZ016MmxqYkFZU05wY3dZCmYwR3NSUytoZ2dURlNPOGdnalo0
        TWxXNU1oajVLTDRoOVMyR1Z2clh4UTQKLS0tIEhUM1M1RHVEcmdic1hQUEV4R0tT
        bk05TjZ3SlN4bVRacUpMdHI0SjY5QmcKilpZv56wLb4q/GGq/WkOg+nG5Z/uk20S
        1dmFTGvZJp0+73TCmDnr7MMqDBIbNdVohgU1gNna9gk+5D+sR+fsPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T22:16:16Z"
  mac: ENC[AES256_GCM,data:wjK6Gy1pVklycTCQ+SmsMBuquQQw0qG0BjebAQ/rqqJ+UJj1hOBUpEt8ErdaT7SM2ZxKmXG8ue5o0dBm+8g/078UPx6RSm/s/ZqWvabUen2TKSUlEhhqXEfD8x754hEXBpkIXcGCwIW3LK2pSIsif4YykBmWa5skI+nD34DWME8=,iv:gql/42mqwkRKw0f5njWfxbjfCiQq1bzy1MR4lJ4PJCw=,tag:PcdcyP1L4P9R+smzmqq8iw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
