---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: bkp-psql-v16-4
spec:
  schedule: "0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: psql-v16-3
  target: prefer-standby
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
