apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wTpDyebWXI0=,iv:2s9KehtS+jsWgdKWmbkAWKqN47bABOzvnfl0Mz5piG4=,tag:XyzRBH5Umcs9v2m71PsQPg==,type:str]
    password: ENC[AES256_GCM,data:YvRcUr/uLLI5VxUa,iv:aT5dSzWd0J9m5wqVpIZ19n78A8wiazdnppOvC40sdjM=,tag:1rVU/UDVvsMt+7qRr/oz6A==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:PJVAJ1Amc2KkhnTiII0gcEaxBiw=,iv:OiSqQ+4rBUoEkQf7rbNNCcqMNDJyNEVQpM8hdZb3NHI=,tag:ZWUzVLuDMqZOHcQmRlh7VQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:pLb+ZoIFP5Rcz3GWWg1WQf+ZH84OgSTUF8TF4F5Ht8Xh+vZBaLnxiQ==,iv:Za2wgsrRmErbnlis7uJiODg603LiYeUdpAjFub5fXRU=,tag:4ATHdBSOh1ezFI9ZWDiSkw==,type:str]
    GARAGE_ACCESS_KEY: ENC[AES256_GCM,data:GfpbwqX4loQ9cYw4LkmvJCGAoLjgcKIETf8=,iv:mPnOwLjUKpfngivl+T3vR9EyudPumbbQJEc6ONbv1WY=,tag:uH1QunrC2nYQ4Pxmwz5ZSQ==,type:str]
    GARAGE_SECRET_KEY: ENC[AES256_GCM,data:KroZHAiGLIwZV820IQ4Z004rhjvoOUof7R3JQ0UHCw7oYoYnBBETUmLFqCGCHQnMrpQOLokrATMEpIOTTnwOEg==,iv:544sN/1Nrcl77my2y+tkj0RIT7JyHC3YAl0rwiNRRuc=,tag:QfF4nybN690z5kP9ViJgYg==,type:str]
    GARAGE_S3_REGION: ENC[AES256_GCM,data:b7TZv8cl2FOG,iv:90+aYDaHmPV3Qx5QRcb5dvr4z9i9e8emiCDXvY3rbBE=,tag:XUo5FdEgk6tWb3nailUgMw==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWThHa0tpSzR0eE40WEdk
            eG5VTWExNTRoeS95K1paTzk1SFB5bDZMOFVJCmV2LzdoNnN5R1A2dTlPVkVINEZI
            NUFFcGtGMTFqa3M2UzZPZWNpWGd0bTgKLS0tIDRZVk5aOHV6R0xzWG0zRWtyNkh3
            R1dxZXpGWStrOXdVWjFZV3ZvUmsycXMKU4MSsMfoCPoPRxSVwok0pPP7OlydCnyP
            aCBHurDBXWa93OR+b1/+kE4t82saBOuRSy/Yo9GsJaibsgkhw/EkXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:17:01Z"
    mac: ENC[AES256_GCM,data:nytaSiOO9Uu5QBEMNA/NWf4KQgEZqsEBHPP8orUOXy4BwRpZlqTpSbjb4BowOsrtOTiPa7Rba9AsvHZU/Lbprko0qV8Su3jyM8oHGuxWCSUHypylkevnMXqAp0NsmVfkISJBB+jaKs83sITafZYjnH0Jw0WpK6VuY3T6N/PBT9w=,iv:K84dYIRJHImMXcPHlpE2XeK/Xl8xicGjnYRo0cFuRDY=,tag:+53ItrKyhqWztSaiYK+kEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
