apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wTpDyebWXI0=,iv:2s9KehtS+jsWgdKWmbkAWKqN47bABOzvnfl0Mz5piG4=,tag:XyzRBH5Umcs9v2m71PsQPg==,type:str]
    password: ENC[AES256_GCM,data:YvRcUr/uLLI5VxUa,iv:aT5dSzWd0J9m5wqVpIZ19n78A8wiazdnppOvC40sdjM=,tag:1rVU/UDVvsMt+7qRr/oz6A==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:PJVAJ1Amc2KkhnTiII0gcEaxBiw=,iv:OiSqQ+4rBUoEkQf7rbNNCcqMNDJyNEVQpM8hdZb3NHI=,tag:ZWUzVLuDMqZOHcQmRlh7VQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:pLb+ZoIFP5Rcz3GWWg1WQf+ZH84OgSTUF8TF4F5Ht8Xh+vZBaLnxiQ==,iv:Za2wgsrRmErbnlis7uJiODg603LiYeUdpAjFub5fXRU=,tag:4ATHdBSOh1ezFI9ZWDiSkw==,type:str]
    GARAGE_ACCESS_KEY: ENC[AES256_GCM,data:M7KP9Cm3HRmiUaPXr2Wk0Ws9V08qoKW+RpU=,iv:njz/A35ybD5uUW5VSeywb0ZSTklq6JRfI5EdZvXovvQ=,tag:+v6lENebSJGyZ6Ai1zo7jQ==,type:str]
    GARAGE_SECRET_KEY: ENC[AES256_GCM,data:4h+WHvG7JqIJh7584v9vXBJxx1RkyA9X7xZzPQ8Ty73VyPHeNjcqfnw/JfhRk1PZ/3t/DkLiWZgKvPAtiJr1Tw==,iv:Z9YMh0ojhsY7l59FgY8ObNp2RZG7vDJ3kpgcrKZlhro=,tag:BZWuHWY5EGnGDDkyHGK5vQ==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWThHa0tpSzR0eE40WEdk
            eG5VTWExNTRoeS95K1paTzk1SFB5bDZMOFVJCmV2LzdoNnN5R1A2dTlPVkVINEZI
            NUFFcGtGMTFqa3M2UzZPZWNpWGd0bTgKLS0tIDRZVk5aOHV6R0xzWG0zRWtyNkh3
            R1dxZXpGWStrOXdVWjFZV3ZvUmsycXMKU4MSsMfoCPoPRxSVwok0pPP7OlydCnyP
            aCBHurDBXWa93OR+b1/+kE4t82saBOuRSy/Yo9GsJaibsgkhw/EkXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T08:15:37Z"
    mac: ENC[AES256_GCM,data:aeK5I3htkxkf5Xs7DJKlf2dR1ChNr7V07a5pG3YfZ0F6B5S1lQ2Mng5/2X82mrDvlcsPmSIsE2bDFfVznbb4POZEDpdXu2b0/V+Kn26opEE9/OonWvVDUa6Iptgxv0qF47cW0NYXZyjN0zM94twbVeclZaD5fxGdXd2o7z27Z1U=,iv:qZx4MVa1itVlS8SOOj86m4qKLvCkWGeMKUd73Hpx0UI=,tag:M74ceOlS6NpmduHUW3tUdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
