apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  namespace: default
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:wTpDyebWXI0=,iv:2s9KehtS+jsWgdKWmbkAWKqN47bABOzvnfl0Mz5piG4=,tag:XyzRBH5Umcs9v2m71PsQPg==,type:str]
  password: ENC[AES256_GCM,data:YvRcUr/uLLI5VxUa,iv:aT5dSzWd0J9m5wqVpIZ19n78A8wiazdnppOvC40sdjM=,tag:1rVU/UDVvsMt+7qRr/oz6A==,type:str]
  S3_ACCESS_KEY: ENC[AES256_GCM,data:PJVAJ1Amc2KkhnTiII0gcEaxBiw=,iv:OiSqQ+4rBUoEkQf7rbNNCcqMNDJyNEVQpM8hdZb3NHI=,tag:ZWUzVLuDMqZOHcQmRlh7VQ==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:pLb+ZoIFP5Rcz3GWWg1WQf+ZH84OgSTUF8TF4F5Ht8Xh+vZBaLnxiQ==,iv:Za2wgsrRmErbnlis7uJiODg603LiYeUdpAjFub5fXRU=,tag:4ATHdBSOh1ezFI9ZWDiSkw==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWThHa0tpSzR0eE40WEdk
        eG5VTWExNTRoeS95K1paTzk1SFB5bDZMOFVJCmV2LzdoNnN5R1A2dTlPVkVINEZI
        NUFFcGtGMTFqa3M2UzZPZWNpWGd0bTgKLS0tIDRZVk5aOHV6R0xzWG0zRWtyNkh3
        R1dxZXpGWStrOXdVWjFZV3ZvUmsycXMKU4MSsMfoCPoPRxSVwok0pPP7OlydCnyP
        aCBHurDBXWa93OR+b1/+kE4t82saBOuRSy/Yo9GsJaibsgkhw/EkXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T21:09:34Z"
  mac: ENC[AES256_GCM,data:Q2rvBb9ZqDNfXifJDAMn2gM2Za2CQ5BAyf75yh0POlwHOBVpP+5oOQMxW/yR54R4r0ZoIu96+yUU0Eb16LLLNmPHywL2hgwbfqrY0aF5bYF/yExR18dmxgFk2h/RwH842gh6yLRcziGQMhk1j8SLyJkJPPkhP5qmj4MNtD9saao=,iv:wwrS7nnSgmcy60+T/pCExyH18/mQIOk47yvk6NqGVfc=,tag:l2rqgVwLX1ueIr0w95moLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
