apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:l5AamwJb10Llb07yP4FirrsoEQYfGYZxHrJdhvz3ZAk=,iv:iaTkxHIHTerE5WTYqX8oUeub7yymxO1jbfqbXFTj684=,tag:ytvwl+SbhyS5lFYOF6ao+w==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbHFvZU5uUTRLRDNqSmZi
        TFZNdDF2eUNZdjhDS05uNUVxRlg4bmVaSlI0CmVLak56VEFZRDFZVm9vYTllY2pK
        MHl3NXpSWVVTYUZsd0l5bXc1Vk85bWcKLS0tIFZibklVekVRejUzZytUL25SREVa
        TFhFSkNQcEt2azBsUng4aHJ6dFhnR3MKqZSWXtDO9H31JzYe8gJ4kqV9QvHWqRcj
        ioHFoXVxhfl4rieYK5TDjBZxFCTuFHcw7EH8aJoC8NseBIBQ5jlntw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T22:16:16Z"
  mac: ENC[AES256_GCM,data:Hx014SdwvVgYSjInKXOIlAXRtXgca8NpZ0pFktt8umXNCJd9ZvSz3k/NfY6sO86x00iFYvosn413XbU/p0uDiBO3CFz08TQC+WUFs9otJRauJd+dPu3F8qHAdR6V3Kv9muzTBN+J4gX07pWiIIiqKAEf9d8ZJ2CixbLMmU69iCY=,iv:Um0+f5EJukh8zYziL9JUhXTxdZA6aq0DvkQbwWlj20U=,tag:o0O92iFu8wfSy/KzfnhARg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
