apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:zj5u6+IV9HL/KwZlnHupvyRx2Qg4Q/rpphRemgrUHnU=,iv:qWrF3NTJrCcQzXjL5Qypezu+a8nNJxsCNNuEnIfPLmc=,tag:eF1WfLQHJxDr+QRnQsDjuA==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3RudnAzSkRKSlVEK0g5
        bnBhOXNrZEZaSXR0TG1icjVhY2xJZ2ErSHdJCnBxRVFWencxYnlOQ1pLWUoxY2N0
        WE5FMnl0bW8vdWhNNEY1aXBHK3hmK3cKLS0tIHY1bk44Z0dsZWNSZ2NWR05sWXNG
        c3U5VlVrMzhFdkJTQXRZMkpKSTcyL2sKBn/HrM8nj9JzacBUoU9Zso/I132lPSn9
        i5MKkhh2BJawNkpY1anPF5GaP0qt2xXgdlcN+fRKoGq3tEc8n+H7Cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:33:07Z"
  mac: ENC[AES256_GCM,data:fTJkQuphBqwDmWXkaAwtDN5SgtDWWFuBJrXqhcO9NLlQdohHDEjF3+wNG1O8ViEYMNvoWO4MZdwNdXCTRpGM61db4YPkHlZn41jKC5s9AZV7DRIWLnhm0H5UbX1eksFCMhbh7j6or8GdMPSV9qb2Q1+DTcpxp/3iiZntCWNqiIk=,iv:GbNE0Xr73Bwig+8N0sgqHQU+oGSt8uo3D4/SR05CKbc=,tag:aO0LybA/bGgfCfxdDl1ZPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
