apiVersion: v1
kind: Secret
metadata:
    name: byd-re-secret
stringData:
    BYD_USERNAME: ENC[AES256_GCM,data:Tr25/QOMt6OXy1TGkh90leivGTgOaoQbqpo=,iv:zDQGdAOf3NO8goUkGXmFnrYvcPX4KWT+BdM0c7DgxqQ=,tag:t7e8lwa+o0YENpRFmeGsiQ==,type:str]
    BYD_PASSWORD: ENC[AES256_GCM,data:TWe1Eng99+Ee0+9kPU3uf3SvwtY=,iv:va9HKE29u+Sa2P23/a54/NHciYtbwSDd1KF0l32q4ck=,tag:hnAP9LpT1NorgycSmx7Pug==,type:str]
    BYD_COUNTRY_CODE: ENC[AES256_GCM,data:7kY=,iv:qOTcAy7GYfs1Rnd51cxPQKxCyRBK0uM+Mrh42RzmqN0=,tag:4+t24A8WfEFyBIZbgKGFbQ==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXpFQzEvRkFsUlhTaG1k
            cytRaUxsZUkvYzA3S0dObi9FaVNqTUtjc0dnCi9QU3IvVzdibXhaZm9pU01YaGNG
            TXdVK2ZQaVlWMGwvVlN1Q3ZvYlZ1M2cKLS0tIHEzZFh2eTZRL3daWmJGRHoyMExp
            a1NjWllSZzZDWDY2cDVMczhDV1FpVzgKZSitFEXhypzX1LrlTlradFS4+9I5C/YC
            F7qG7EBJJAw2ol1LQ+cco0Letzc+NAk3jwgyBHklqo+RSvwWlVeTrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T22:11:02Z"
    mac: ENC[AES256_GCM,data:M5mW1Cgo+UZnQM8zpPQJ3IZriwc4ErG+3K3YIIPvo2M8/RPBPxXCy6P4Ba5sDqbINYiLtiN0L2KxVEtPY6udJOtD6sJd61Fi1q3R6UeR0oZmv0uptp0aOm3ESfVsB1i5HqcmJ2sO2wefKnFTwqDPnJG528T1b5eLFuQhnjl8D/k=,iv:qTzv9VOHKUcB6bHc8bcRXFM52bp1LkuoZCODrOo32lE=,tag:BvwiigkTYCeIMAQBcHZEdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
