apiVersion: v1
kind: Secret
metadata:
    name: byd-re-secret
stringData:
    BYD_USERNAME: ENC[AES256_GCM,data:xJT4qCf7U8Z0j/m+85sIbYEV5Gwn,iv:JQ/n4IApj/MFa9HwqPtUuzijtZlS3gTuw5EcEc3MGII=,tag:S3SMcNJ+SrtQdw2Srfkmxw==,type:str]
    BYD_PASSWORD: ENC[AES256_GCM,data:O+sOEIJgNZUGN0I7UC2GaHx0d5Y=,iv:SlDrarkxYlua1nei7Axo0vVdHWlsjP5X+wMGQ4dIWzQ=,tag:2XlAUTn46UASFWdL6d4JTQ==,type:str]
    BYD_COUNTRY_CODE: ENC[AES256_GCM,data:I2c=,iv:AH/ej4e3aFwbLA67q7V/WCaCt4PfBxSmldbjGcpd38Y=,tag:bevgdqjyK5Mk5OlcfbeQ2w==,type:str]
    BYD_VIN: ENC[AES256_GCM,data:BJvZ63pSnZwrF4K9KuwhhlM=,iv:B5ZB34s6heTA1vRnWUY6yHzqTK6jvhK8Kch+OFu/UgQ=,tag:OtijR8DwID9/9v/vGzB59Q==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXpFQzEvRkFsUlhTaG1k
            cytRaUxsZUkvYzA3S0dObi9FaVNqTUtjc0dnCi9QU3IvVzdibXhaZm9pU01YaGNG
            TXdVK2ZQaVlWMGwvVlN1Q3ZvYlZ1M2cKLS0tIHEzZFh2eTZRL3daWmJGRHoyMExp
            a1NjWllSZzZDWDY2cDVMczhDV1FpVzgKZSitFEXhypzX1LrlTlradFS4+9I5C/YC
            F7qG7EBJJAw2ol1LQ+cco0Letzc+NAk3jwgyBHklqo+RSvwWlVeTrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T22:18:53Z"
    mac: ENC[AES256_GCM,data:R4Cqw0y02A2yMayRNVbvR4A7MRaRsskLzfeDBRvng8v39KgPqTWXWJEjI1y7sIktqFYwZnYGjIwFzRmjirxr4adxLMQRagimhyuMoszTfUlAmpbbIUyihk34wql2Im0DwbSKYpsfx9YNM+WJUEX7Uxv3zR+3b9GILfUpXaUvcBE=,iv:b+vELWanQi5KvgHbYblLZ48ZZyR6AxY3ZpahEf3MyoM=,tag:vMUyiTcpPw55lj8Jq9+OXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
