apiVersion: v1
kind: Secret
metadata:
    name: byd-re-secret
stringData:
    BYD_USERNAME: ENC[AES256_GCM,data:Tr25/QOMt6OXy1TGkh90leivGTgOaoQbqpo=,iv:zDQGdAOf3NO8goUkGXmFnrYvcPX4KWT+BdM0c7DgxqQ=,tag:t7e8lwa+o0YENpRFmeGsiQ==,type:str]
    BYD_PASSWORD: ENC[AES256_GCM,data:TWe1Eng99+Ee0+9kPU3uf3SvwtY=,iv:va9HKE29u+Sa2P23/a54/NHciYtbwSDd1KF0l32q4ck=,tag:hnAP9LpT1NorgycSmx7Pug==,type:str]
    BYD_COUNTRY_CODE: ENC[AES256_GCM,data:I2c=,iv:AH/ej4e3aFwbLA67q7V/WCaCt4PfBxSmldbjGcpd38Y=,tag:bevgdqjyK5Mk5OlcfbeQ2w==,type:str]
    BYD_VIN: ENC[AES256_GCM,data:BJvZ63pSnZwrF4K9KuwhhlM=,iv:B5ZB34s6heTA1vRnWUY6yHzqTK6jvhK8Kch+OFu/UgQ=,tag:OtijR8DwID9/9v/vGzB59Q==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXpFQzEvRkFsUlhTaG1k
            cytRaUxsZUkvYzA3S0dObi9FaVNqTUtjc0dnCi9QU3IvVzdibXhaZm9pU01YaGNG
            TXdVK2ZQaVlWMGwvVlN1Q3ZvYlZ1M2cKLS0tIHEzZFh2eTZRL3daWmJGRHoyMExp
            a1NjWllSZzZDWDY2cDVMczhDV1FpVzgKZSitFEXhypzX1LrlTlradFS4+9I5C/YC
            F7qG7EBJJAw2ol1LQ+cco0Letzc+NAk3jwgyBHklqo+RSvwWlVeTrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T16:11:36Z"
    mac: ENC[AES256_GCM,data:O0A5KJtWqq8XIFhdgeK0KUeQjsy917ZR7WhVVtUrHBCCgJpyILDzwTTdpmQDUeLk4rj2mVMbH3XWHyUwlBxXyhUU2HzkinHRrAk3X0SAfXUMfslPmL5XRBp5zgkBIW87FSfp1zqJmjy1n9B61WwNdHa5OWs2UzYDq9rRsuexync=,iv:fTXlc6G+SSKMPgZoaipJvCxHVSedgZgIZ4iyL7FmvHI=,tag:ApmINaXySLD4EVF84k5ULw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
