apiVersion: v1
kind: Secret
metadata:
    name: byd-re-secret
stringData:
    BYD_USERNAME: ENC[AES256_GCM,data:Tr25/QOMt6OXy1TGkh90leivGTgOaoQbqpo=,iv:zDQGdAOf3NO8goUkGXmFnrYvcPX4KWT+BdM0c7DgxqQ=,tag:t7e8lwa+o0YENpRFmeGsiQ==,type:str]
    BYD_PASSWORD: ENC[AES256_GCM,data:TWe1Eng99+Ee0+9kPU3uf3SvwtY=,iv:va9HKE29u+Sa2P23/a54/NHciYtbwSDd1KF0l32q4ck=,tag:hnAP9LpT1NorgycSmx7Pug==,type:str]
    BYD_COUNTRY_CODE: ENC[AES256_GCM,data:HkY=,iv:jHH3IUBkUewfSfKyiPMtXMhv7TKS5qFuu8SIhwWmFw8=,tag:+WLDttS54rtXX14ZrWz70w==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXpFQzEvRkFsUlhTaG1k
            cytRaUxsZUkvYzA3S0dObi9FaVNqTUtjc0dnCi9QU3IvVzdibXhaZm9pU01YaGNG
            TXdVK2ZQaVlWMGwvVlN1Q3ZvYlZ1M2cKLS0tIHEzZFh2eTZRL3daWmJGRHoyMExp
            a1NjWllSZzZDWDY2cDVMczhDV1FpVzgKZSitFEXhypzX1LrlTlradFS4+9I5C/YC
            F7qG7EBJJAw2ol1LQ+cco0Letzc+NAk3jwgyBHklqo+RSvwWlVeTrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T14:02:01Z"
    mac: ENC[AES256_GCM,data:FUdO+5u6fLUAmhMyBdAVuPnp5yMrcx3Rmf25SHXQja4s3BogwKnJ0L3La5BoKOzvqgR/UjQ4dFCoDHi+Cl7BWbKbD5F3nT0ymOpK0VBG/aKdysaGRdHclDOYsuH5drGdWdEGmhrKKp3FSGHgkdUlyh8T2ZEC8kHmL4JCalfV2aU=,iv:FPtw+jsnAyMFCOuu1SHGgbiCaulsuTFQ1449gpyQQW8=,tag:pBZB3VA9+IpMwn3IH9nyMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
