apiVersion: v1
kind: Secret
metadata:
    name: byd-re-secret
stringData:
    BYD_USERNAME: ENC[AES256_GCM,data:Th0JuuyGB26P07tm3kex+Xe+FP69wA==,iv:3dXRQ0SfaohT9aVeUkdUZHuUWz4N9N7EkFOZl/sMqHQ=,tag:HvxsDln3v2dG3nss5pT59w==,type:str]
    BYD_PASSWORD: ENC[AES256_GCM,data:gMh4/B1WsOrwaM35UA==,iv:8YMPQHA5w/lmwqjKLGHJ7+RQHOnqFlTgJcEHUP161NM=,tag:m5LlQqLVWsH9pBeg0+mSgA==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVXpFQzEvRkFsUlhTaG1k
            cytRaUxsZUkvYzA3S0dObi9FaVNqTUtjc0dnCi9QU3IvVzdibXhaZm9pU01YaGNG
            TXdVK2ZQaVlWMGwvVlN1Q3ZvYlZ1M2cKLS0tIHEzZFh2eTZRL3daWmJGRHoyMExp
            a1NjWllSZzZDWDY2cDVMczhDV1FpVzgKZSitFEXhypzX1LrlTlradFS4+9I5C/YC
            F7qG7EBJJAw2ol1LQ+cco0Letzc+NAk3jwgyBHklqo+RSvwWlVeTrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T21:47:53Z"
    mac: ENC[AES256_GCM,data:WwH0lj7CYUZJ5bigYn0m/Iqmqtabs72qZisMcy0osjEX4iUWN5W2upMAhTMNRu1aDAsfbuAgjHYk+rj2jZP21efo0z6jt/SklLSltP1TCTFu9Z+Z4Ii8p+e35E4Gvqg7+t1SV5tMYgDFdp2mm9Iz+jQ8UkdhmuGpCIjWbXpcicI=,iv:rmtGG6PMXRoIlJjAgt+cDl3CAzYAyAIhk6bPa8W979A=,tag:P8GyQru4I4OK5OG8GC+Nsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
