---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./echo/ks.yaml
  - ./tautulli/ks.yaml
  - ./actual/ks.yaml
  - ./esphome/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./prowlarr/ks.yaml
  - ./plex/ks.yaml
  - ./mosquitto/ks.yaml
  - ./node-red/ks.yaml
