apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:dWaQRPVbPOPQw1EDUXbBJ+j1WrHQPbQ2SOowJBNH4L6PCdrbGsEOcVPFYS0lpXIVCQHjabVqfXiuDQmJD84uNpgHbO4+tozH1ZUwIxe2fV910e95jqBMkBOhHP99diS6Rz098VAAbbTRKvdHp9QYqBcaOabYLA2TGN/Wcvlff8chp7t7+2gJEnj93pMUcDKRN1EHk5dCcNdhD4perexxchUry/asbLsHVZwiwb45Fox9sg9H,iv:54H5FCNhcXL8r5ZMEsjahZQGaKpVCusHWkFl52XZAx0=,tag:s4k1YG5xui24x4lOtWNXOA==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcU5ZLytYUFlTQlRZU0JQ
        YjVySmdjcThFaEQyaDhHaElXQlo3RTNxVjFzClU0NkRkL3dXNUpOMkRLclBGa1R3
        emhsQTZlcTQ3MDhGTndPaFl3WUFsTmcKLS0tIC84UjgwTDBUdGFndTMwdkFDb1Jq
        VWh6ZG03Rlh5YWxwWWZKZ0ZpeDc2Z3cKTC/BUkYLb8mkDN4UYPCNR/cUyLeDOGK/
        L0OT/hRIY4a/rE+MHf4i3WJy2PfDsfkt3B7ezVN2uGdl6hU5s6lkqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T22:16:16Z"
  mac: ENC[AES256_GCM,data:j7GzY5Pw3LqUESxnr+p3Afc06WFv8tpi66hacKJTNNRt6ssbUW9jpdL47+GXwwPNNJgQ/HRgc3sRsZagiZi6028b3409EU61MXJpX3zIG0aIiv8E0S4vKQn3P/43uAmdeWDod/hqqghhuHEgaU8th9Jxfvig17O663gn3fPLucc=,iv:ht4l5mSvdrhzzkxraOv0R8DJ9mkLGkkw4yNc3txgs2c=,tag:9TYxfNkL52djYyRTzPxICA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
