apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:QmuS4jl3mZ09h9KnhWOQ4eNXwuFC3OoWjC5XaPoSvTufwqTSSAc+OgUS6DqtVk8vMNyxozP6ZLpEdClx1XFstKD6xyLPBXuArES6pXX/tYw6d0CeVxT6NKojgsQq+Y0o9MbYDJF3IQV3YFtxihnXTu5D6iXtxJrnTHQ0niS3D4K4w3Gomwes6BggiTS9aY2lG5v6PNvWMQJfcqf/ZSxRVzZQCJxxtKkYqNfSYb/YJenTdyMj,iv:f4yftk+OF7VGFn+GWsZum7+Gcdu5PR7Nb+In8GccP/Y=,tag:i8LykIdfdJoB8Aa2gkGgbA==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYVk2VHB0MnhiVFltU3RE
        NFdMWk9vOUl3eDBhYTRHY3hWcktUa2w3NlNjCjJaajFxbVdORjZDbXR6UWI3aXAv
        RnNoSlcvUU1JcHR5dndTdzdHQjMxd0UKLS0tIEloSm5HMkRkSkpQdHBhNm8vTnd1
        dEtLbHdtN0U4cG1zMklOOEwyR1hGV1UKBrtXs72OVFNcLQAGoIRUfIy9zx74k0li
        DH6+GHpI0ZWKhh8djuEzEbEHMY2D0kjJQvFWqdO3kY+g2kzUnkY4Ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:33:07Z"
  mac: ENC[AES256_GCM,data:zIyn+zC/8VPEtOBPYwsUOT5QLub2Grdmz9N/V1KweBfbnGGKteCOqH0HTnDfIeJ60ABkqGuwimHhN4gWAC+rAL12UWwYaHLkPjLHEqR5CmvLNzkGuI7yuiJTiILukoc3WxX64NlJrkcCLiW8vuQsfv7JJlsvuYNsTksOtel4Vo0=,iv:UAO5mOaPDqLhbKupnBKDq+teWXvDLpiyqdT1NXLkxHk=,tag:n/XgV2FOELbw6lx2zLQjPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
