apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:m+iukQg17KKucXzqHb9/QlM/F+jGRyK9fy+OvphlWuM=,iv:OGKjnb571eaXfg8fmhi5VmgBbVQGFZOArb4tDayFNJM=,tag:78UAxoIaam/ONoqqTmAl/w==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVm5OR0xUeVRTQk04clhp
        Q3hZa1V2bUtob3QxMGFkc054Mm5vaGVnVzFzCkNZR2grb3NpeCs3SkNnd09uUWd0
        MDVVcDJnbklvL0pPUDFqQjJoekYydEEKLS0tIGNZNFA3STFXZ0VIejJ1ejRXalBi
        Uzg1dWhVSmcwWldySzR3bUNFNjZmTEUKJVSKykPjCka53VJtJ9S5fDqfeIqGpz+z
        EofIrPWDITrHrB6qd4XVZ56yeMSGvw0gLTJhk9JhOWP5Bk2cHBWSBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T10:22:16Z"
  mac: ENC[AES256_GCM,data:NIFmQR9iIehSOiTUSw//89dSfO+g36OjsZTJi91Rrp3Ng+dzpGNZSgTfC2SQ4X6Uv+eVUFUOlAxPd9z+W5b75+BTCZosLNES5pE3Kc0BQNfXnt6cWfbYUY6CBXrwJNKNllL58I1o+cQ/6xWiULI2fACgADLLpR93fiin2Tf/z3M=,iv:tJVMr3YkI2Krqwy1gMS0U1iDWK3lGRUaZ5ZiSVTh+Hs=,tag:ugzZ0kYFXhJ4ao9iymibEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
