apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:JCD4xkN/k7jMOho3lpG0GzNuB5s0s9CgRD32q1NuFe3Ayv3snvGoww==,iv:7vQEn+1gMF1TCcGa5JqyAaCll4kLT5sMenO8ZlJcWj4=,tag:Hr5eTiiwkPAp//kxpMSoZg==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VzJ4WUNQR280YkZxT0w2
            dnBoOG9GVGs1bFZWUVRyc2lucFJnVFNlWVI4CjNIdXRJbXArTGg5c2llRVZ4SWV2
            aXBOVlkzQy9nSjE4Zmo0Nm84VWxNbTQKLS0tIEEvQzV5U3U1T0tISWpnUzJyRDhT
            VmQ4SzFvSHZXdjNyWTNiZkhyeHBieWMK7kw9CKNK0FVYUejw8sXtWPQefroo609S
            1/J8nJSY4bCNHWGWq+2OI5aaOHOg2sJI3j6dOpSDAmxmYbJxHNGf6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T21:20:01Z"
    mac: ENC[AES256_GCM,data:hycyGoZNKbpcjeCAHnUruBG6YC1vyse80E6uFGci+io08Y8DGWTWHurlZgSxh+Yw5foG6mkMxaJNPPJlCG6xRBJ1rxXLSFOjJX45U0IP8b1tIJHKt/e1YQmtFDt3VErOw9Y7brGS0xwsEDpUXGO47kEZY5ztj2cF0vGyam36Bbk=,iv:TDcKmmcp7izS2x6bJUmzR0ar4W8u8cAoBmLLoJZGpPo=,tag:yO+VxgDiIXW6CLtzvFAf9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
