apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:dh1+1znamCM7blZKmfz7gJx9Azn4f4v9H+dytFikacLVkul/AwvcJw==,iv:BR+gRj+ivfVHReUhGJ4p5fYIgc2aDPefJF14blr4xBA=,tag:AmW0WGxiupIJVWnWjPdNmQ==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VzJ4WUNQR280YkZxT0w2
        dnBoOG9GVGs1bFZWUVRyc2lucFJnVFNlWVI4CjNIdXRJbXArTGg5c2llRVZ4SWV2
        aXBOVlkzQy9nSjE4Zmo0Nm84VWxNbTQKLS0tIEEvQzV5U3U1T0tISWpnUzJyRDhT
        VmQ4SzFvSHZXdjNyWTNiZkhyeHBieWMK7kw9CKNK0FVYUejw8sXtWPQefroo609S
        1/J8nJSY4bCNHWGWq+2OI5aaOHOg2sJI3j6dOpSDAmxmYbJxHNGf6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:33:07Z"
  mac: ENC[AES256_GCM,data:kVuX5lIgOGpAsvXSue8NQ3nPUHySB069pC0BFb47ziZbPbnJr6pW3egq0R4QaZzXArfgtlkz+DgXmM4WcKVIJTcvP8NZvNWK9g/wunCLBo1fSVlKTfAS+1QDe/t6F9vKdhOMDRq76MO7eYd/ngXXdPczOJ5NSUbfvP3V5MaxbOA=,iv:IOr4rvV8OoS6ir2jYCckqoENaS+bsRXXeVz9FQhnjvw=,tag:wnhazTYpIguAwYFqlV1sGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
