apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:EGF1i2KfGR2siP4hKDc+5QOEyAsiJexhs5uB0EwzaomsaBfRBu/HRQ==,iv:kafk7QeEabJ1aBFC26ZdToUjrKdvafWtuC77BYXQlrs=,tag:jRA9T9NRAQNsIbbgb/jqkw==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdmdZTlVKVUJnS1VuVTcy
        U1BJVFFDQzN6NWhQSVUrUjhlbzkwbGxwaWo0Ck5TbkxheHF1UFN1YXJnNHdES2tq
        d0ZYQzZzMFFmRG94Mzd0Qi9FRlRaY3cKLS0tIC9KYlNrUVU2QnJieVV1aitBdVZP
        SFM3bWR2TUVIUTBEbnBUcW0xVFFrNU0Ki49ueSVMQ+KK+oFGMTc4itHkoxTyhSmL
        81IHWiV1mS93zw44BXpXPrl8rOxAMnJVbDNsID10+tiiloSw78dwlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T22:16:16Z"
  mac: ENC[AES256_GCM,data:UfQdM9N9xKcon5jD1pb4NzLqyGWCnIzaPaftI0ovlYCinTmE84p95B85r+O1i+6H4XPuj2Anf8cnKXF8lity8C3HEcPMZLS6WLh5xdbHPbJ9caMSN2cYtqnOkHnwIEC+5ZRkQY0hQbaLck9OGzDhhAtBVSOg+q2wLwddNcwb5fo=,iv:E7OPwuaWeapK54KvfMSbcddET6qlClEcOelVhQCLNAw=,tag:daDAK4PP/fL6o0AIFTQCyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
