apiVersion: v1
kind: Secret
metadata:
    name: zero-ssl-eabsecret
data:
    secret: ENC[AES256_GCM,data:soBka+9A670XSMn9lHWQYmcEiRbRYyM/ll7lXT34KP+c5d4K/71A096AloGyaQ2grzmwwUgq1A95qVQiS4UQIFdebRC2GKlrssCpGyNX1r9PZw1N9hsZQf7ZayGAGD7f60pn1uB5JO5LGuv/o9ZzipPmOPI=,iv:UZd5/u3nE8XYJwN3MqGQh7IqB/O63/EXW7mY5X7XFV8=,tag:4BEdrvXPti2bY8uxL6iPgQ==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvemlrM1pHOXR6L1RnZmlP
            RzNCb2N3RHJYcXYyTUQ3TEozWGIybjBqZnlzCmR3Snk4YWU1WDJoSjFLMDgrRXlF
            QmlZek5xM3BMQTB4Z3I0TGo2MDN6ZUUKLS0tIFgreVFkb0t2Z2VMRkQyU0FnUC9w
            T2lXL0NKcEJ0ZHR4M1hOVWpNMlMvcDQK0AZuAySfiJ6c9rkysTBHTyz5ymfB6KjY
            GMNggPLcUgQd/dwWgTTPrlivNC0t5amQ52uuAU0T/aWFrpaXESmOSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T21:11:05Z"
    mac: ENC[AES256_GCM,data:Er9GYonRcsBoX6/+U7CeNt2nFqtq/OoIi/AtILdAEmE/2s/QK8Bl1TLQSNC3L1D1swNl0tHuoKBFcJevxeB8wFx3PC0qVvGIHvkXU67P7MbNgxQA29zn8OeQUrX1Yeny5uaZNTThMIj0WOcx7NP+oQpGjxb3qSHJbJ9Aj5yYtQ0=,iv:st7594b0w3ZRgf5V0qDrw1fspNT0O1IFuHFJOPo+R/o=,tag:bZ68u4zGlpNwnCujiIevtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
