---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./nfs-docs.yaml
  - ./nfs-docs-volsync-idrive-secret.yaml
  - ./volsync-docs.yaml
  - ./nfs-videos.yaml
  - ./nfs-videos-volsync-idrive-secret.yaml
  - ./volsync-videos.yaml
