# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nfs-docs-volsync-idrive-secret
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:9Yq9JbEgpf/9hXy7q5oAl78bLwOuuH8IQ3mPDRlgNRWAUlcwnjomknHh8K6b/V3i,iv:qY9nRpzHYucl3XGgpKXq3DA2s1N6J+VgJtezEGgi3Ic=,tag:xtXQRmxibFJfXkBIcsLLIw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:n/8y2/CU4YjPLtKEV156rPxCzsZDiQ==,iv:PJN9p5NuUtD5k77DtqasHYwBrHaycpxj6YKhT74zbUY=,tag:Fdu3YWnkDMPyos8Xmt5Yqw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CBrMZZkVbf5GNbpj7jQG87OCARU=,iv:ao3t4I5hDi3T1zPPu6fG0JdXyjifJy80eKy7kUayvyE=,tag:ozUDddYsINH99gi1hGiZNA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FbcpOVFo/Xbhl5mbRMOxOmltNWjYffd5Q9ByhtsJb1efeAwRl1Ep7g==,iv:ibWJW8L/qbm+YWwFpjQ2j0MZ5z0aZFqJCzFto8Ry3gc=,tag:RqLFr2qLU5xvR4cwRwey4A==,type:str]
    RESTIC_PACK_SIZE: ENC[AES256_GCM,data:ydA=,iv:JN/w3hEv4B00PV6N8NSF2tESW8BNcFtT5sp0BhDMq9A=,tag:0mIrGFpVFUA3wOLO9BoBqw==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHFZcjFrQ0NTZXhLbG90
            cWRYVlhXRk5tSUlVcmdobU05VnphN0NNZ1VrClNjU1FocWxjYWRGT0JGM3lQNEtV
            UHVzbm54ODJ4dUliaG9VRDhKMk1UeTQKLS0tIDZHK1VkNmQ4b2NXYkIycXlBQUp0
            MkpQRlpYYUJ0YmUrYThzdVBXcUNZOFEKQtOlwba5KbAMcT4wMYRabmIXJRR5kDAk
            xK+bPlrZVoFjFzH3xcwu6czyvtz8GJz+AKtXBk1V3GzNHO8qK9osaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T19:23:39Z"
    mac: ENC[AES256_GCM,data:furkor2X5rOjmefqwve8Rej4oxY583HLM90Yq5CTm4rQZCQRm0Ovz9byQ7nRQ2zXgZvN7EheAos0X5Iqqb5cTnIZmuT49A2r0Rg3pEQt7aZxYq4eqslHpHK4XiX/SPQZXmm9vrxSOzT/oxDGFWqAVoN6LdhGWirwTgOUh5k5waw=,iv:kptCuBXDI6NjwBbQykJIKrNZlXoGTvVNlUONIs7tp2s=,tag:QqSqfUK4iyvtZkSr9pVc+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
