# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nfs-videos-volsync-idrive-secret
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:rSvRO6bOHWqlLL1hUp/u1LI5vyTkKTaHptNpIujzf64/0tLAQOk5lCOEmRaBPA==,iv:WRkN3hDECl7CFojuGeKajenmK6Z0LaLjxKYsa71PxHk=,tag:LBQ/X+P3VUMM7nGqzFvCVw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:n/8y2/CU4YjPLtKEV156rPxCzsZDiQ==,iv:PJN9p5NuUtD5k77DtqasHYwBrHaycpxj6YKhT74zbUY=,tag:Fdu3YWnkDMPyos8Xmt5Yqw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3D8NtGXYLXRPcBOjYvrrLtwq7GI=,iv:XZLNa1x1fMcxdzv7aSiYi6d8kQyMGG4CpWEKD17Rs0I=,tag:RtWVmhz62hgvKRBQGT2BLg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wqF19UUCR71WeDtm8CZUVhNvMJKtxpfcPKFEd5wIQe50Xw8PNckxNQ==,iv:6WbMlW8c2rOaDNPu4/04VGktKu+uAoWM9WGOIFWGIKc=,tag:oDjqRttv09PCzq6PkYP7nw==,type:str]
    RESTIC_PACK_SIZE: ENC[AES256_GCM,data:ydA=,iv:JN/w3hEv4B00PV6N8NSF2tESW8BNcFtT5sp0BhDMq9A=,tag:0mIrGFpVFUA3wOLO9BoBqw==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHFZcjFrQ0NTZXhLbG90
            cWRYVlhXRk5tSUlVcmdobU05VnphN0NNZ1VrClNjU1FocWxjYWRGT0JGM3lQNEtV
            UHVzbm54ODJ4dUliaG9VRDhKMk1UeTQKLS0tIDZHK1VkNmQ4b2NXYkIycXlBQUp0
            MkpQRlpYYUJ0YmUrYThzdVBXcUNZOFEKQtOlwba5KbAMcT4wMYRabmIXJRR5kDAk
            xK+bPlrZVoFjFzH3xcwu6czyvtz8GJz+AKtXBk1V3GzNHO8qK9osaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T19:13:25Z"
    mac: ENC[AES256_GCM,data:lIdvrXWq08Qrsl953TirXgqLCrLPmt9EWfNyy2tvaTbapuMf5jX3qxtflxAwnloaaYBgN0mZGupBq/vQ5+ZespdCXEK8E3rvSKt6ZHqIyKKsc4imhuJYc9SrvKySlw0Ns7Hn2loFiuTWIa1r5eV1OKyCGkxkTeWyWnLddbYdtRA=,iv:nfshgTq0NaRU66sHru62aZoxDLeOpoCR6qrI9s+YIw0=,tag:qGdMGtWHGfrH0269tb+qig==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
