# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nfs-videos-volsync-idrive-secret
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:mIPzet/ePfcqAzpy8dRMxzgOcrczRgulxDoo80oj9zaKJaijZDdVgNz4Xbjt,iv:556bwuAQNTvrMmzsvS6sixPzS6i5PUrrmRVAPQ/nIUE=,tag:Dh/lF9S5iX1etCkLCfb1/w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:n/8y2/CU4YjPLtKEV156rPxCzsZDiQ==,iv:PJN9p5NuUtD5k77DtqasHYwBrHaycpxj6YKhT74zbUY=,tag:Fdu3YWnkDMPyos8Xmt5Yqw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Gh7ISjmCloQmY4q6v/PdA5cNhuY=,iv:UChDdd7VsQPUFwGoJfM5ePX/Vjbcm1dnyRB//uPL1PY=,tag:ATpBxi0YCzuDaR+uBFIiTA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:G1JpnTM1orBidNjy5Hl6eISkt18AbyLrrsNeg0kiDXRD779SmLrMDg==,iv:k+o02nj3pEQ2MIVIhJUmwMWwZ/jVNlQRUMRdIr+qDf4=,tag:4C1TLT0NXrKMYbYHLRppxQ==,type:str]
    RESTIC_PACK_SIZE: ENC[AES256_GCM,data:ydA=,iv:JN/w3hEv4B00PV6N8NSF2tESW8BNcFtT5sp0BhDMq9A=,tag:0mIrGFpVFUA3wOLO9BoBqw==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHFZcjFrQ0NTZXhLbG90
            cWRYVlhXRk5tSUlVcmdobU05VnphN0NNZ1VrClNjU1FocWxjYWRGT0JGM3lQNEtV
            UHVzbm54ODJ4dUliaG9VRDhKMk1UeTQKLS0tIDZHK1VkNmQ4b2NXYkIycXlBQUp0
            MkpQRlpYYUJ0YmUrYThzdVBXcUNZOFEKQtOlwba5KbAMcT4wMYRabmIXJRR5kDAk
            xK+bPlrZVoFjFzH3xcwu6czyvtz8GJz+AKtXBk1V3GzNHO8qK9osaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T19:24:48Z"
    mac: ENC[AES256_GCM,data:vY3bT/F1RkPQkGRlz7hxsZyMvAN6Vl7vTXtXvmZHf5ZXVSZ8ZRYKibnmQPmDtUMA0tnq/vjPEbNgcwQ1GZd1LA6xoZPNS2Jmyj5+icPTW5edZb23m2ElPe79C3qw/nup5a2td6k8QYLZ2PQyJtWZAQBDtVV9gpeV81uMuG1rktM=,iv:8EcMI6NWU1gNo5WYi90rLAcAw9wUXXZyZqfNLTW7KFg=,tag:xNLaNMjOQhmfkSEke6uF/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
