# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:u6/vY7xPx8oZ106Tk6nbvK77NRs=,iv:CgAkV976Xu3ZrpF6cLniMInubD5McfJ0xraqoZNiM88=,tag:a59h+81flUlaIiszDrP8Ww==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHFZcjFrQ0NTZXhLbG90
            cWRYVlhXRk5tSUlVcmdobU05VnphN0NNZ1VrClNjU1FocWxjYWRGT0JGM3lQNEtV
            UHVzbm54ODJ4dUliaG9VRDhKMk1UeTQKLS0tIDZHK1VkNmQ4b2NXYkIycXlBQUp0
            MkpQRlpYYUJ0YmUrYThzdVBXcUNZOFEKQtOlwba5KbAMcT4wMYRabmIXJRR5kDAk
            xK+bPlrZVoFjFzH3xcwu6czyvtz8GJz+AKtXBk1V3GzNHO8qK9osaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T21:09:23Z"
    mac: ENC[AES256_GCM,data:KhOgc3KDE7QX0Eq26KFkaw5n/Ym/5hcKa7y9b1RvTAp2ClgnN+l/7kj7ljhCYwQ8MaOv11N+0989cbDz+KzqwuawN3+Z+lk19Z6aGjAvjHyEvjF40LQfSi06jL95b9Y15KYaMXskWqzfmLeLi8NUYR1xpbPzBEOataPiCYgYn/8=,iv:sDMFPcG/3MvwMvYpxWQtt7VYJpCk75XzXdS6kbowJ+Y=,tag:Kxg5aIMe8g7nYZOUNIdF4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
