apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: default
type: Opaque
stringData:
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:/kPE/NmlHKoY4/BRLbEp8nWnWV7htr2nCDTYLbpL28kYS+l4ITKH98sD4KEUmivJ7zyc4UCvtIF29OZ1BwODGPFqEaHNZlESrrjBOaL2CjwjIVLGKRLIsZtpm5uti6NZg9n+pp2tVJEiL1k4xlwzx6jhn9l9fDT4B+/6KY8rTg==,iv:lUwflYp1ccK+Vez1Ur3htwd0mFVni+1mBMwpmj0RfGw=,tag:O+CbXqgXMhzk8oDzvqcz3w==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdkJ4RjRzU0xaMWZubEwy
            Uk9Ea2N1aE1PeUxrdTVocXNrUG5kTHRCcXg4Cm8wbWhsUXRuam9YNlkvYzBhbjhi
            azV2cGx0NkpBS0JzVWZhM1I1QW1xaUkKLS0tIDl3YVVndmhxUmlZZ1VRVzVpSTJy
            WVQvajFzQXFpdjhKZGFOUVhFTTVhblUKt8fSO3feT9wq3/a1y+vEbwFdbJWFpdJg
            3ciEYg4VGs5eosNUJEzqaaJTbtdnppjtNHiGxWakr7cy8/GIZFoMvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T23:11:28Z"
    mac: ENC[AES256_GCM,data:/mMUm/4yQlSGn0i7gM2Z640MgR8zkD3L+aAj2Hsfu4ps+bUaSG4PHsVljifqqNB43orUxBXLE1mIjBtm9RZUGymmXnRRT/N2p2U3GYJD3OwoxJ1DHQ+cvGkYxUfathgpFh55Cy6wFDeuVS9KtuFda85X3i6oTPqwRHtY9NYzIuU=,iv:LVvLlgrrwB95hqfRJHoqy/ulR5cIU4bBbhnfRZxgYzo=,tag:UudAGg7x9jDA78JqlTwmoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
