apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secret
  namespace: default
type: Opaque
stringData:
  HASS_POSTGRES_URL: ENC[AES256_GCM,data:Lm6pzl73fhaIf8JReIBF+mTp50I8sVwNXM26t5jOeIWa5KhJzwINugZm0WNk2gO9KaM3+3Ix26WU31Hk93PbVkdSkv50PvbN2t793IqvAgMbk7qUhvfusdC0gLCNlX9PgFHHYGuII9B0vGTCS9B/zYKocB5RZ32t6m88TXoUsg==,iv:zTmfOGxYvVdvtGOFFbF8sEhPOj3lzVukkoVZ3GqHVQ0=,tag:9G0+DyHafbqe57gSBJwmZw==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdkJ4RjRzU0xaMWZubEwy
        Uk9Ea2N1aE1PeUxrdTVocXNrUG5kTHRCcXg4Cm8wbWhsUXRuam9YNlkvYzBhbjhi
        azV2cGx0NkpBS0JzVWZhM1I1QW1xaUkKLS0tIDl3YVVndmhxUmlZZ1VRVzVpSTJy
        WVQvajFzQXFpdjhKZGFOUVhFTTVhblUKt8fSO3feT9wq3/a1y+vEbwFdbJWFpdJg
        3ciEYg4VGs5eosNUJEzqaaJTbtdnppjtNHiGxWakr7cy8/GIZFoMvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T22:04:09Z"
  mac: ENC[AES256_GCM,data:oUqymG2NQlEcJ28rUfzT4Tn2+4pV/TOlkP0N1o2QkALRaAA3YdN0BMJ0kIEHR/BdHLm0bo1caBJyPOq+qymCALoDwsP+aS9kUG0LwJ1Cu+5PSslJBng/y0hA82dLJTfBAQnP3nofXJcKh9WRTj1FpjUHAmZ1zyYjKYGhWpNqUZI=,iv:0xHs8fpz7RMOigBvKEyi9oGG9OGKN3p0427OfYUsRB0=,tag:Qgashsk9jk9KJzDk2aJ20Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
