---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  interval: 1h
  values:
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      enableLiveness: true
      serviceMonitor:
        enabled: true
      # Zero CSI resources to prevent pending pods
      csiCephFSPluginResource: {}
      csiCephFSProvisionerResource: {}
      csiRBDPluginResource: {}
      csiRBDProvisionerResource: {}
      csiNFSPluginResource: {}
      csiNFSProvisionerResource: {}
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources: {}
    # Zero all Ceph component resources
    cephClusterSpec:
      resources: {}
      mon:
        resources: {}
      mgr:
        resources: {}
      osd:
        resources: {}
      mds:
        resources: {}
