apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:5hzbbvEYIX8ZfpkMdzKv,iv:p4Z4WjNvl+Qe6Ew+VStesw0754/XMdU/65u/kYFT8t8=,tag:rTLZ3SHvKl+zc6RiSJbIpg==,type:str]
sops:
  age:
    - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS2tkcEw2TFptRFFabFdm
        ZG9Ha1QrWFdFMWdZSXV4bmpZZ3BYKzhKU2dNCitqeTVienJHQll1a2JnaGNGSUt0
        T0VPelRzdDJ2VHdHOU5RT2h4UlBva2cKLS0tIHZ4UmtuZktkMEZVa29XNXYyZEx2
        aHpPbWxaUDRqNkMvVUFoeUNaQlVqWncK2hUsn2mOeSnKJ4smItBPmoD3LNyHLEo1
        A8C24hp+pQjGgTnWalkY5UKiKpoY4MlUJNaZkf/jlpQUQknA9yZPAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T09:42:26Z"
  mac: ENC[AES256_GCM,data:JtmdfxFKXDN+AoopWjlUm87b2dC83xebndIxjuvzBdxI9NsVAmrXf76ZnOfaUwlkPz2/2x231VPWXeVkqlz2mc5cqx7H9yWEyqW2ZXtfTZH6okFp2ldvHp8CukXc2vJsWYvCEIj//CGa8MxTvrZHaPTf/0FwGNdmVBOTgMWCj7Q=,iv:CP76hbYksjQdv6p686qfKsB49O4Y3/+uRxTdD69dhCQ=,tag:LcvNHjmdl2TryyzpmBtqzA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
