apiVersion: v1
kind: Secret
metadata:
    name: garage-secret
type: Opaque
stringData:
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:3sow9YZVDoXJTjmjv0qBE24k8oHZhWPKCxa2gmyoDj5Sj7uLa9zgDjMQsQq1iEiRc7TlkxIPCJj7Sd5JJPzpLA==,iv:WaQDtCT0Ij5IJf09M7VbBLMgDHVPObwPyaId/IySCc0=,tag:LomSBABLTFNEgc1WVhR4SQ==,type:str]
    GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:V2vLxYcz9V26bRSnngXPdqK0x/O7o1I8krIZVAuJ04xumyBekMur2siQkV4=,iv:wNaTcBAoFFZ3AfCt6T1ooM9Y9lIktfdgmlvz+XHVR/E=,tag:TQdO/gAkk20R41eQE5Y+ug==,type:str]
    GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:3fxPJsMH98NGH7WmgKsn6WFp5O5nZrTFzlDVNmbKVVm92tsQ4IL/OtBPOPo=,iv:UfrsTEJGG6Y6+/UmK89wT5lzfP3prmKv45GQFF0mI3I=,tag:VnzfRDotPW3ByjVXJ2cqsg==,type:str]
sops:
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NElIVzlla0VadlFXUDNQ
            MEhucWJKclpLcGdKVTk1dUVJTTJzbzF6RGpZClNsd0tGcG5zdXhMWlVTNmhUQ2w1
            eGFWS3FRM1c0RWd4YWtGNm9uK3VXZDAKLS0tICt1dFA1azQ0bXVNQzZabmY2Njda
            R3B0anVWN3d6cmgwdW02a2NWWEJHUDAK53lb9NxVUQRIlwr0kpK4oRAoz75AUrty
            7qr95RkRoeW+66w7PUd5UypvQvs5Kkw1MDnY4ANXaYbkel/rGMhrJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T21:55:54Z"
    mac: ENC[AES256_GCM,data:n6O+2npdnqp15S/oETQsSgx+8ZamZf5R5rBU2Rt9yg7F2GKrAO3F2F5T01qSnqATCUcPKmSNRBieuZe8Io8WHfTJiNXif3tcnXwfnW+LAPCHn54C8K1O+fWUK9/gpQpdalaBUTmxqTSiEwXbr0nNteTQzxiedwvKyoumPtMGVJI=,iv:SkdT1XLrqSVKZw7iCDKy4yuVeTCCg84JExqyWeD08ms=,tag:LFEz6esPTqrMfxC2nDhNgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
